name: Test all functions nightly
on:
   schedule:
      - cron:  '0 0 * * *'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: 956d5681-0351-4924-943f-be59e132876f
